export const items = [
  {
    id: 0,
    name: "Baza Trainee Ukraine",
    inProgress: true,
    img: "/images/slides/baza2-min.png",
    link: "https://baza-2-front-one.vercel.app/ua",
    utilities: [
      "Next.js",
      "Next Intl",
      "CSS Module",
      "Zustand",
      "TanStack",
      "Axios",
      "Js-cookie",
      "React Hook Form",
      "Next Js TopLoader",
      "Swiper",
    ],
  },
  {
    id: 7,
    name: "Baza CRM",
    inProgress: true,
    backend: "https://github.com/baza-trainee/baza-crm-backend",
    img: "/images/slides/crm-baza.png",
    link: "https://baza-crm-frontend.vercel.app/",
    utilities: [
      "Node.js",
      "Express.js",
      "TypeScript.js",
      "TypeORM",
      "Docker",
      "Bcrypt",
      "CORS",
      "Discord.js",
      "Dotenv",
      "Jsonwebtoken",
      "Nodemailer",
      "Swagger UI and JSDoc",
    ],
  },
  {
    id: 1,
    name: "44th Mechanized Brigade",
    img: "/images/slides/donate-min.png",
    link: "https://44-zbir.vercel.app",
    utilities: ["React.js", "React Modal", "CSS Module"],
  },
  {
    id: 8,
    name: "Events",
    img: "/images/slides/events.png",
    backend: "https://github.com/Anastasiia-Ihn/events-tech-back-end",
    link: "https://anastasiia-ihn.github.io/events-tech-front-end/?page=1",
    utilities: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Mongoose",
      "Bcrypt",
      "CORS",
      "Dotenv",
      "React Router",
      "Axios",
      "React Hook Form",
      "React Modal",
      "CSS Module",
    ],
  },
  {
    id: 2,
    name: "TaskPro",
    img: "/images/slides/tasks-min.png",
    link: "https://boommmeran.github.io/team-five/welcome",
    utilities: [
      "React.js",
      "Node.js",
      "Express.js",
      "Redux Toolkit",
      "Redux persist",
      "React Router",
      "Axios",
      "Formik",
      "React Modal",
      "Styled components",
    ],
  },
  {
    id: 3,
    name: "Rent cars",
    img: "/images/slides/cars-min.png",
    link: "https://anastasiia-ihn.github.io/rentCars/",
    utilities: [
      "React.js",
      "Redux Toolkit",
      "Redux persist",
      "React Router",
      "Axios",
      "Formik",
      "React Modal",
      "Styled components",
    ],
  },
  {
    id: 4,
    name: "Movies",
    img: "/images/slides/films-min.png",
    link: "https://anastasiia-ihn.github.io/movies/",
    utilities: [
      "React.js",
      "Axios",
      "React Router",
      "Styled components",
      "Date-fns",
    ],
  },
  {
    id: 5,
    name: "Apps for Managing Contacts",
    img: "/images/slides/contacts-min.png",
    link: "https://anastasiia-ihn.github.io/phonebook/",
    utilities: [
      "React.js",
      "Redux Toolkit",
      "React-redux",
      "Axios",
      "React Router",
      "React modal",
      "Redux persist",
      "Styled components",
      "Yup",
      "Formik",
    ],
  },
  {
    id: 6,
    name: "Chocolate project",
    img: "/images/slides/food.png",
    link: "https://oleg-kaniuk.github.io/chocolate-team-project/",
    utilities: ["HTML", "JavaScript", "CSS"],
  },
];
